"""D76 O-AI-controlled exact Google OAuth subjects."""

from __future__ import annotations

from app.contracts.gmail import (
    GMAIL_CREDENTIAL_PROVIDER_ID,
    GMAIL_CREDENTIAL_SCOPE,
    GMAIL_CREDENTIAL_SECRET_REF,
    GMAIL_PLUGIN_ID,
    GMAIL_PLUGIN_VERSION,
    GMAIL_READ_CAPABILITY_NAME,
    GMAIL_READ_CREDENTIAL_PROFILE_ID,
)
from app.contracts.google_calendar import (
    GOOGLE_CALENDAR_CAPABILITY_NAME,
    GOOGLE_CALENDAR_CREDENTIAL_PROFILE_ID,
    GOOGLE_CALENDAR_CREDENTIAL_PROVIDER_ID,
    GOOGLE_CALENDAR_CREDENTIAL_SCOPE,
    GOOGLE_CALENDAR_CREDENTIAL_SECRET_REF,
    GOOGLE_CALENDAR_PLUGIN_ID,
    GOOGLE_CALENDAR_PLUGIN_VERSION,
)
from app.contracts.google_oauth import GoogleOAuthCredentialSubject

GOOGLE_CALENDAR_OAUTH_CALLBACK_PATH = (
    "/api/v1/oauth/google-calendar/callback"
)
GOOGLE_GMAIL_OAUTH_CALLBACK_PATH = "/api/v1/oauth/google-gmail/callback"

GOOGLE_CALENDAR_OAUTH_SUBJECT = GoogleOAuthCredentialSubject(
    profile_id=GOOGLE_CALENDAR_CREDENTIAL_PROFILE_ID,
    provider_id=GOOGLE_CALENDAR_CREDENTIAL_PROVIDER_ID,
    plugin_id=GOOGLE_CALENDAR_PLUGIN_ID,
    plugin_version=GOOGLE_CALENDAR_PLUGIN_VERSION,
    capability_name=GOOGLE_CALENDAR_CAPABILITY_NAME,
    scope=GOOGLE_CALENDAR_CREDENTIAL_SCOPE,
    secret_ref=GOOGLE_CALENDAR_CREDENTIAL_SECRET_REF,
    callback_path=GOOGLE_CALENDAR_OAUTH_CALLBACK_PATH,
)

GOOGLE_GMAIL_OAUTH_SUBJECT = GoogleOAuthCredentialSubject(
    profile_id=GMAIL_READ_CREDENTIAL_PROFILE_ID,
    provider_id=GMAIL_CREDENTIAL_PROVIDER_ID,
    plugin_id=GMAIL_PLUGIN_ID,
    plugin_version=GMAIL_PLUGIN_VERSION,
    capability_name=GMAIL_READ_CAPABILITY_NAME,
    scope=GMAIL_CREDENTIAL_SCOPE,
    secret_ref=GMAIL_CREDENTIAL_SECRET_REF,
    callback_path=GOOGLE_GMAIL_OAUTH_CALLBACK_PATH,
)

GOOGLE_CALENDAR_OAUTH_AAD = GOOGLE_CALENDAR_OAUTH_SUBJECT.aad
GOOGLE_GMAIL_OAUTH_AAD = GOOGLE_GMAIL_OAUTH_SUBJECT.aad

__all__ = [
    "GOOGLE_CALENDAR_OAUTH_AAD",
    "GOOGLE_CALENDAR_OAUTH_CALLBACK_PATH",
    "GOOGLE_CALENDAR_OAUTH_SUBJECT",
    "GOOGLE_GMAIL_OAUTH_AAD",
    "GOOGLE_GMAIL_OAUTH_CALLBACK_PATH",
    "GOOGLE_GMAIL_OAUTH_SUBJECT",
]
